### PR TITLE
JBIDE-20068 - Show in Web Browser via Livereload Server doesn't work

### PR DESCRIPTION
**Pull request by xcoulon**
Enforcing jetty dependencies to 9.2.10 to avoid ClassNotFoundException because
DevStudio included a mix of 9.2.9 and 9.2.10 versions.

### CODE REVIEW

**Comment by fbricon** [comment]
+1 to apply

**Comment by mickaelistria** [comment]
@xcoulon Would be nice if you could trigger manually the jbosstools-livereload_4.3.mars on jenkins as soon as you've merged it.

**Comment by xcoulon** [comment]
@fbricon thanks for the +1
@mickaelistria here you are: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/JBossTools/view/JBossTools_4.3.mars/job/jbosstools-livereload_4.3.mars/20/ ;-)

**Comment by maxandersen** [comment]
+1 :)

**Pull request merged**
